(let ()
  (save-snapshot-and-exit (third *command-line-args*))
  (if (> (length *command-line-args*) 2)
      (binding ((*package* %user-package))
        (load-as "script" (third *command-line-args*)))))
