(define (print-em-all)
    (let ((argc (#/lang/%argument-count)))
      (when (>= argc 1) (print (#/lang/%load-arg 0)))
      (when (>= argc 2) (print (#/lang/%load-arg 1)))
      (when (>= argc 3) (print (#/lang/%load-arg 2)))
      (when (>= argc 4) (print (#/lang/%load-arg 3)))))

(print-em-all)
(print-em-all 0)
(print-em-all 0 1)
(print-em-all 0 1 2)
(print-em-all 0 1 2 3)
