(print (length '(1 2 3)))
(print (length "hello there"))
(print (length '()))

(print (* 1 2 3))
(print (* 1.0 2.0 3.0))
(print (* 1 2.0 3))

(print (+ 1 2 3))
(print (+ 1.0 2.0 3.0))
(print (+ 1 2.0 3))

(print (- 1 2 3))
(print (- 1.0 2.0 3.0))
(print (- 1 2.0 3))

(print (/ 1 2 3))
(print (/ 1.0 2.0 3.0))
(print (/ 1 2.0 3))

(print `(expecting #t))
(print (= 1 1))
(print `(expecting #t))
(print (= 1 1 1))
(print `(expecting #t))
(print (<= 1 1))
(print `(expecting #t))
(print (<= 1 1 1))
(print `(expecting #t))
(print (< 1 2))
(print `(expecting #t))
(print (< 1 2 3))
(print `(expecting #t))
(print (<= 1 2))
(print `(expecting #t))
(print (<= 1 2 3))
(print `(expecting #f))
(print (= 1 2))
(print `(expecting #f))
(print (= 1 1 2))
(print `(expecting #f))
(print (<= 2 1))
(print `(expecting #f))
(print (<= 1 2 1))
(print `(expecting #f))
(print (< 2 1))
(print `(expecting #f))
(print (< 1 3 2))
(print `(expecting #f))
(print (<= 2 1))
(print `(expecting #f))
(print (<= 1 3 2))

'done
