(define *s* (make-string-output-stream))
(%string-output-stream-write-char *s* #\x)
(%string-output-stream-write-char *s* #\y)
(%string-output-stream-write-char *s* #\z)
(%string-output-stream-write-string *s* " hello, world ")
(%string-output-stream-write-char *s* #\z)
(%string-output-stream-write-char *s* #\y)
(%string-output-stream-write-char *s* #\x)
(print (string-output-stream-get-string *s*))
