(define str " abcdef")

(print (char-code-at str 0))
(print (char-at str 0))
(print (char-at str 1))
(print (char-at str 2))
(print (char-at str 3))
(print (char-at str 4))
(print (char-at str 5))
(print (char-at str 6))
