(define *s* (make-string-output-stream))
(#/lang/%string-output-stream-write-char *s* #\x)
(#/lang/%string-output-stream-write-char *s* #\y)
(#/lang/%string-output-stream-write-char *s* #\z)
(#/lang/%string-output-stream-write-string *s* " hello, world ")
(#/lang/%string-output-stream-write-char *s* #\z)
(#/lang/%string-output-stream-write-char *s* #\y)
(#/lang/%string-output-stream-write-char *s* #\x)
(print (string-output-stream-get-string *s*))
